parameters:
    # Defaults to Memcached adapter
    ninja_mutex.adapter.class: NinjaMutex\Lock\MemcachedLock
    ninja_mutex.implementor.name: memcached
    
    ninja_mutex.class: NinjaMutex\MutexFabric

services:
#    ninja_mutex.memcached:
#        class: Memcached
#        calls:
#            - [ addServer, [ %memcached_host%, %memcached_port% ]]
    
    ninja_mutex.adapter:
        class: %ninja_mutex.adapter.class%
        arguments:
            - @session.memcached
        
    ninja_mutex:
        class: %ninja_mutex.class%
        arguments:
            - %ninja_mutex.implementor.name%
            - @ninja_mutex.adapter
